/**
 * PDF Renderer — converts investigation final reports (Markdown) into styled PDF documents.
 * Uses Puppeteer for high-fidelity HTML→PDF conversion with a professional PRD-style template.
 */

import puppeteer, { Browser } from 'puppeteer';

// Singleton browser instance to avoid re-launching Chromium for each export
let browserInstance: Browser | null = null;

async function getBrowser(): Promise<Browser> {
    if (browserInstance && browserInstance.connected) {
        return browserInstance;
    }
    browserInstance = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    });
    // Clean up on process exit
    const cleanup = () => {
        if (browserInstance) {
            browserInstance.close().catch(() => { });
            browserInstance = null;
        }
    };
    process.on('exit', cleanup);
    process.on('SIGINT', cleanup);
    process.on('SIGTERM', cleanup);
    return browserInstance;
}

/** Close the browser singleton (for graceful shutdown) */
export async function closeBrowser(): Promise<void> {
    if (browserInstance) {
        await browserInstance.close().catch(() => { });
        browserInstance = null;
    }
}

interface InvestigationMetadata {
    id: string;
    status: string;
    target?: string;
    timeRange?: string;
    category?: string;
    model?: string;
    correlationId?: string;
    incidentId?: string;
    productName?: string;
    contestCount?: number;
}

/**
 * Convert a Markdown investigation report to a PDF buffer.
 * Uses a lightweight Markdown→HTML conversion (no external library needed — 
 * Puppeteer renders Markdown via GitHub-style CSS if we convert it ourselves).
 */
export async function renderPdf(
    markdownReport: string,
    metadata: InvestigationMetadata
): Promise<Buffer> {
    const html = buildHtml(markdownReport, metadata);
    const browser = await getBrowser();
    const page = await browser.newPage();

    try {
        await page.setContent(html, { waitUntil: 'networkidle0', timeout: 15000 });
        const pdf = await page.pdf({
            format: 'A4',
            margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
            printBackground: true,
            displayHeaderFooter: true,
            headerTemplate: `
                <div style="width:100%;font-size:8px;color:#94a3b8;padding:0 15mm;display:flex;justify-content:space-between;">
                    <span>Investigation Report — ${escapeHtml(metadata.target || 'N/A')}</span>
                    <span>${new Date().toLocaleDateString()}</span>
                </div>
            `,
            footerTemplate: `
                <div style="width:100%;font-size:8px;color:#94a3b8;padding:0 15mm;display:flex;justify-content:space-between;">
                    <span>Generated by Investigation Dashboard</span>
                    <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
                </div>
            `,
        });
        return Buffer.from(pdf);
    } finally {
        await page.close();
    }
}

function escapeHtml(text: string): string {
    return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/**
 * Lightweight Markdown to HTML converter.
 * Handles the common patterns found in investigation reports:
 * headers, bold, italic, code blocks, tables, lists, links, horizontal rules.
 */
function markdownToHtml(md: string): string {
    let html = md;

    // Fenced code blocks (```language\n...\n```)
    html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_, lang, code) => {
        return `<pre><code class="language-${lang || 'text'}">${escapeHtml(code.trimEnd())}</code></pre>`;
    });

    // Inline code (must come after fenced blocks)
    html = html.replace(/`([^`]+)`/g, '<code>$1</code>');

    // Tables (simple pipe-based)
    html = html.replace(/^(\|.+\|)\n(\|[-| :]+\|)\n((?:\|.+\|\n?)*)/gm, (_, headerRow, _separator, bodyRows) => {
        const headers = headerRow.split('|').filter((c: string) => c.trim());
        const rows = bodyRows.trim().split('\n').filter((r: string) => r.trim());
        let table = '<table><thead><tr>';
        headers.forEach((h: string) => { table += `<th>${h.trim()}</th>`; });
        table += '</tr></thead><tbody>';
        rows.forEach((row: string) => {
            const cells = row.split('|').filter((c: string) => c.trim());
            table += '<tr>';
            cells.forEach((c: string) => { table += `<td>${c.trim()}</td>`; });
            table += '</tr>';
        });
        table += '</tbody></table>';
        return table;
    });

    // Headers (# through ######)
    html = html.replace(/^######\s+(.+)$/gm, '<h6>$1</h6>');
    html = html.replace(/^#####\s+(.+)$/gm, '<h5>$1</h5>');
    html = html.replace(/^####\s+(.+)$/gm, '<h4>$1</h4>');
    html = html.replace(/^###\s+(.+)$/gm, '<h3>$1</h3>');
    html = html.replace(/^##\s+(.+)$/gm, '<h2>$1</h2>');
    html = html.replace(/^#\s+(.+)$/gm, '<h1>$1</h1>');

    // Horizontal rules
    html = html.replace(/^---+$/gm, '<hr>');

    // Bold and italic
    html = html.replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>');
    html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');

    // Unordered lists
    html = html.replace(/^(\s*)[-*]\s+(.+)$/gm, '$1<li>$2</li>');
    html = html.replace(/((?:<li>.*<\/li>\n?)+)/g, '<ul>$1</ul>');

    // Ordered lists
    html = html.replace(/^\d+\.\s+(.+)$/gm, '<li>$1</li>');

    // Links
    html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');

    // Line breaks — convert double newlines to paragraphs
    // First, protect block elements
    const blocks = html.split('\n\n');
    html = blocks.map(block => {
        const trimmed = block.trim();
        if (!trimmed) return '';
        // Don't wrap block-level elements in <p>
        if (/^<(h[1-6]|pre|table|ul|ol|li|hr|div|blockquote)/.test(trimmed)) {
            return trimmed;
        }
        return `<p>${trimmed.replace(/\n/g, '<br>')}</p>`;
    }).join('\n');

    return html;
}

function buildHtml(markdownReport: string, meta: InvestigationMetadata): string {
    const startDate = !isNaN(Number(meta.id)) ? new Date(Number(meta.id)).toLocaleString() : 'Unknown';
    const reportHtml = markdownToHtml(markdownReport);

    // Build metadata rows
    const metaRows: [string, string][] = [
        ['Status', meta.status.charAt(0).toUpperCase() + meta.status.slice(1)],
        ['Target', meta.target || 'N/A'],
        ['Started', startDate],
    ];
    if (meta.timeRange) metaRows.push(['Time Range', meta.timeRange]);
    if (meta.category) metaRows.push(['Category', meta.category]);
    if (meta.correlationId) metaRows.push(['Correlation ID', meta.correlationId]);
    if (meta.incidentId) metaRows.push(['Incident', meta.incidentId]);
    if (meta.model) metaRows.push(['Model', meta.model]);
    if (meta.productName) metaRows.push(['Product', meta.productName]);
    if (meta.contestCount) metaRows.push(['Times Contested', String(meta.contestCount)]);

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
    @page { size: A4; margin: 0; }
    
    body {
        font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
        line-height: 1.7;
        color: #1e293b;
        max-width: 100%;
        margin: 0;
        padding: 0;
        font-size: 11pt;
        background: #ffffff;
    }

    .cover-header {
        background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%);
        color: white;
        padding: 40px 32px;
        margin-bottom: 24px;
    }
    .cover-header h1 {
        font-size: 22pt;
        font-weight: 700;
        margin: 0 0 8px 0;
        letter-spacing: -0.5px;
    }
    .cover-header .subtitle {
        font-size: 11pt;
        color: #94a3b8;
        margin: 0;
    }

    .metadata-table {
        width: 100%;
        border-collapse: collapse;
        margin: 0 0 32px 0;
        font-size: 10pt;
    }
    .metadata-table td {
        padding: 8px 16px;
        border-bottom: 1px solid #e2e8f0;
    }
    .metadata-table td:first-child {
        font-weight: 600;
        color: #64748b;
        width: 140px;
        background: #f8fafc;
    }
    .metadata-table td:last-child {
        color: #1e293b;
    }

    .content {
        padding: 0 32px 40px;
    }

    h1 { font-size: 20pt; color: #0f172a; margin: 32px 0 16px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
    h2 { font-size: 16pt; color: #1e3a5f; margin: 28px 0 12px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
    h3 { font-size: 13pt; color: #334155; margin: 24px 0 10px; }
    h4 { font-size: 12pt; color: #475569; margin: 20px 0 8px; }
    h5, h6 { font-size: 11pt; color: #64748b; margin: 16px 0 8px; }

    p { margin: 8px 0; }

    strong { color: #0f172a; }

    code {
        background: #f1f5f9;
        color: #dc2626;
        padding: 2px 6px;
        border-radius: 4px;
        font-family: 'Cascadia Code', 'Consolas', monospace;
        font-size: 9.5pt;
    }

    pre {
        background: #0f172a;
        color: #e2e8f0;
        padding: 16px 20px;
        border-radius: 8px;
        overflow-x: auto;
        font-size: 9pt;
        line-height: 1.5;
        margin: 12px 0;
        page-break-inside: avoid;
    }
    pre code {
        background: none;
        color: inherit;
        padding: 0;
        font-size: inherit;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin: 16px 0;
        font-size: 10pt;
        page-break-inside: avoid;
    }
    th {
        background: #f1f5f9;
        color: #334155;
        font-weight: 600;
        text-align: left;
        padding: 10px 12px;
        border: 1px solid #e2e8f0;
    }
    td {
        padding: 8px 12px;
        border: 1px solid #e2e8f0;
        vertical-align: top;
    }
    tr:nth-child(even) td { background: #f8fafc; }

    ul, ol { padding-left: 24px; margin: 8px 0; }
    li { margin: 4px 0; }

    hr {
        border: none;
        border-top: 2px solid #e2e8f0;
        margin: 24px 0;
    }

    a { color: #2563eb; text-decoration: none; }

    blockquote {
        border-left: 4px solid #3b82f6;
        margin: 12px 0;
        padding: 8px 16px;
        background: #eff6ff;
        color: #1e40af;
    }

    .status-badge {
        display: inline-block;
        padding: 4px 14px;
        border-radius: 16px;
        font-weight: 600;
        font-size: 9pt;
        text-transform: uppercase;
        letter-spacing: 0.5px;
    }
    .status-completed { background: #dcfce7; color: #166534; }
    .status-failed { background: #fef2f2; color: #991b1b; }
    .status-aborted { background: #fef3c7; color: #92400e; }
    .status-paused { background: #e0e7ff; color: #3730a3; }
</style>
</head>
<body>
    <div class="cover-header">
        <h1>Investigation Report</h1>
        <p class="subtitle">${escapeHtml(meta.target || 'Investigation')} — ${startDate}</p>
    </div>
    <div class="content">
        <table class="metadata-table">
            ${metaRows.map(([label, value]) => {
        if (label === 'Status') {
            const cls = `status-${meta.status}`;
            return `<tr><td>${label}</td><td><span class="status-badge ${cls}">${escapeHtml(value)}</span></td></tr>`;
        }
        return `<tr><td>${escapeHtml(label)}</td><td>${escapeHtml(value)}</td></tr>`;
    }).join('\n            ')}
        </table>
        <hr>
        ${reportHtml}
    </div>
</body>
</html>`;
}
