/// <summary>
/// Resolves a default pipeline ID into a full PipelineDefinition.
/// First tries built-in presets, then falls back to user-saved workflows
/// stored in `<investigationsPath>/workflows.json`.
///
/// Builtin presets always win on ID collisions (with a warning logged) so
/// upgrades that introduce a new builtin can never silently take over a
/// user's customized workflow.
/// </summary>
import * as fs from 'fs';
import * as path from 'path';
import type { PipelineDefinition } from './PipelineDefinition';
import { buildPipelinePreset, listPipelinePresets, matchPipelinePreset } from './builtinAgents';

/// <summary>
/// Shape of a single workflow entry in `workflows.json` (subset of SavedWorkflow).
/// </summary>
interface WorkflowEntryLike {
    /// <summary>Top-level workflow id (autogenerated timestamp, not the human-readable id).</summary>
    id?: string;
    /// <summary>Display name of the workflow.</summary>
    name?: string;
    /// <summary>The pipeline definition - its `id` is the human-readable identifier.</summary>
    pipeline?: PipelineDefinition;
}

/// <summary>
/// Reads `<investigationsPath>/workflows.json` and returns the list, or [] if missing or unreadable.
/// </summary>
function readWorkflowsFile(investigationsPath: string | undefined): WorkflowEntryLike[] {
    // Guard against missing/invalid path
    if (!investigationsPath || typeof investigationsPath !== 'string') {
        return [];
    }
    // Build the workflows file path
    const filePath = path.join(investigationsPath, 'workflows.json');
    // Bail if file does not exist
    if (!fs.existsSync(filePath)) {
        return [];
    }
    try {
        // Parse the JSON file
        const raw = fs.readFileSync(filePath, 'utf-8');
        const parsed = JSON.parse(raw);
        // Must be an array
        if (!Array.isArray(parsed)) {
            return [];
        }
        return parsed as WorkflowEntryLike[];
    } catch (err: any) {
        // Malformed JSON - log and return empty
        console.error(`[pipelineResolver] Failed to read workflows.json at ${filePath}: ${err.message}`);
        return [];
    }
}

/// <summary>
/// Looks up a workflow by its pipeline.id (human-readable identifier).
/// Returns the matching pipeline definition, or undefined if not found.
/// </summary>
export function findWorkflowPipelineById(
    pipelineId: string,
    investigationsPath: string | undefined,
): PipelineDefinition | undefined {
    // Read workflows from disk
    const workflows = readWorkflowsFile(investigationsPath);
    // Find the first workflow whose pipeline.id matches
    const match = workflows.find(w => w.pipeline?.id === pipelineId);
    // Return the pipeline (or undefined)
    return match?.pipeline;
}

/// <summary>
/// Resolves an ID to a full PipelineDefinition by checking builtin presets first,
/// then user-saved workflows. Returns undefined if neither matches.
/// Logs a warning when a workflow is shadowed by a builtin with the same ID.
/// </summary>
export function resolveDefaultPipeline(
    id: string,
    investigationsPath: string | undefined,
): PipelineDefinition | undefined {
    // Validate the input
    if (!id || typeof id !== 'string') {
        return undefined;
    }
    // First try builtin presets (always wins on collision)
    const builtin = listPipelinePresets().find(p => p.id === id);
    if (builtin) {
        // Warn if a workflow with the same id would otherwise have matched
        const shadowed = findWorkflowPipelineById(id, investigationsPath);
        if (shadowed) {
            console.warn(
                `[pipelineResolver] Workflow "${id}" is shadowed by built-in preset of the same id. ` +
                `Using the built-in. Rename the workflow's pipeline.id to disambiguate.`,
            );
        }
        // Build and return the builtin pipeline
        return buildPipelinePreset(id);
    }
    // Fallback: workflow lookup
    const workflowPipeline = findWorkflowPipelineById(id, investigationsPath);
    if (workflowPipeline) {
        return workflowPipeline;
    }
    // Neither - log and return undefined (caller will use no default)
    console.warn(
        `[pipelineResolver] No pipeline found for defaultPipelineId "${id}". ` +
        `Checked built-in presets and workflows.json. The system will run without a default pipeline.`,
    );
    return undefined;
}

/// <summary>
/// If the given pipeline matches a builtin preset OR a saved workflow, returns the
/// human-readable ID that can be used in `defaultPipelineId`. Returns undefined
/// when the pipeline is purely custom and should be persisted inline.
/// </summary>
export function matchDefaultPipelineId(
    pipeline: PipelineDefinition,
    investigationsPath: string | undefined,
): string | undefined {
    // Try builtin preset matching first
    const presetId = matchPipelinePreset(pipeline);
    if (presetId) {
        return presetId;
    }
    // Try workflow matching by pipeline.id
    if (pipeline.id) {
        const found = findWorkflowPipelineById(pipeline.id, investigationsPath);
        if (found) {
            return pipeline.id;
        }
    }
    // No match - caller should persist the pipeline inline
    return undefined;
}
